### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by wedoro** [emvaized/open-in-popup-window-extension#6]
Hi, That`s my settings.Drag and drop Version 0.1.2 it is ok,but all newer versions not ok (NOT "TOP RIGHT" ).
![Screenshot 2024-09-13 at 12-04-24 Add-ons-Verwaltung](https://github.com/user-attachments/assets/6445138e-9a98-478b-b0ac-5123631bcbe6).

**Comment by emvaized** [comment]
Hi there! 

In version `0.2` drag and drop behavior was changed in order to open popup window always at mouse cursor position, ignoring the general setting. 

Such behavior made sense to me, because this way you could control the position at which popup will be opened for every link, dropping it at the exact place of the screen where you'd want to see the popup. 

But I see now that this behavior could easily create confusion and be seen as a bug. Maybe I should add an option "Always open drag and drop under mouse cursor" to make it more clear?

**Comment by wedoro** [comment]
Hi,  "I should add an option "Always open drag and drop under mouse cursor" to make it more clear?".Yes,DO IT. THX

**Comment by emvaized** [comment]
New update `v.0.3.2` includes an option to disable always opening windows, which were created by drag and drop, under mouse cursor
